services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn MaxDiscoverHub.wsgi:application --bind 0.0.0.0:2001 --workers 3 --timeout 120"
    restart: unless-stopped
    env_file:
      - ${APP_ENV_FILE:-.env}
    environment:
      DEBUG: "False"
      DJANGO_ENV: production
    depends_on:
      - redis
#      - db
    expose:
      - "2001"
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
  
  celery:
    build: .
    command: celery -A MaxDiscoverHub worker -l info
    restart: unless-stopped
    env_file:
      - ${APP_ENV_FILE:-.env}
    environment:
      DEBUG: "False"
      DJANGO_ENV: production
    depends_on:
      - redis
      - web
#      - db
    volumes:
      - media:/app/media

  celery-beat:
    build: .
    command: celery -A MaxDiscoverHub beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped
    env_file:
      - ${APP_ENV_FILE:-.env}
    environment:
      DEBUG: "False"
      DJANGO_ENV: production
    depends_on:
      - redis
      - web
#      - db

  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

#    Uncomment below for PostgreSQL (if you use it)
#  db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: yourdbname
#       POSTGRES_USER: yourdbuser
#       POSTGRES_PASSWORD: yourdbpassword
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data


#         Nginx service to serve static files and reverse proxy to Gunicorn
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/app/staticfiles:ro
      - media:/app/media:ro
      - ./ssl/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - web
volumes:
    pgdata:
    staticfiles:
    media:
    redis_data:
