

"""
Django settings for MaxDiscoverHub project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import cloudinary
import cloudinary.api
import cloudinary.uploader
import dj_database_url
from decouple import Csv, config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ENVIRONMENT = config('DJANGO_ENV', default='development').lower()

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost',
    cast=Csv(),
)
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1,http://localhost',
    cast=Csv(),
)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'projectApp',
    'socialApp',
    'tailwind',
    'theme',
    'widget_tweaks',
    'django_celery_beat', # Celery Beat
    'cloudinary_storage',
    'cloudinary',
]

if DEBUG:
    INSTALLED_APPS += [
        'django_browser_reload',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

# django-axes admin brute-force protection (pip install django-axes to enable)
try:
    import axes  # noqa: F401
    INSTALLED_APPS = list(INSTALLED_APPS) + ['axes']
    MIDDLEWARE.append('axes.middleware.AxesMiddleware')
    AUTHENTICATION_BACKENDS = [
        'axes.backends.AxesStandaloneBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]
    AXES_FAILURE_LIMIT = 5
    AXES_COOLOFF_TIME = 1  # lock out for 1 hour after 5 failed attempts
    AXES_LOCKOUT_TEMPLATE = None
except ImportError:
    pass

ROOT_URLCONF = 'MaxDiscoverHub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MaxDiscoverHub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


if ENVIRONMENT == 'production':
    DATABASE_URL = config('DATABASE_URL', default='').strip().strip("'").strip('"')
    if DATABASE_URL.startswith('psql '):
        DATABASE_URL = DATABASE_URL[5:].strip().strip("'").strip('"')

    if not DATABASE_URL:
        raise ValueError('DATABASE_URL must be set when DJANGO_ENV=production.')

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Enable WhiteNoise to serve static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ["127.0.0.1"]  # Needed for tailwind dev server


DEFAULT_NPM_BIN_PATH = (
    "C:/Program Files/nodejs/npm.cmd" if os.name == "nt" else "npm"
)
NPM_BIN_PATH = config('NPM_BIN_PATH', default=DEFAULT_NPM_BIN_PATH)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
X_FRAME_OPTIONS = 'DENY'

if ENVIRONMENT == 'production':
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=True, cast=bool)
    CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
        'SECURE_HSTS_INCLUDE_SUBDOMAINS',
        default=True,
        cast=bool,
    )
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False


# Celery settings
from celery.schedules import crontab

CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    # Weekly newsletter — every Monday at 8 AM UTC
    'weekly-newsletter': {
        'task': 'projectApp.tasks.send_weekly_newsletter',
        'schedule': crontab(day_of_week='monday', hour=8, minute=0),
    },
    # Option B: World Bank data → original article (once daily, 7 AM UTC)
    'daily-data-journalism': {
        'task': 'projectApp.tasks.generate_data_journalism_articles',
        'schedule': crontab(hour=7, minute=0),
    },
    # Option C: Nigerian RSS headlines → AI rewrite (every 8 hours)
    'rss-article-rewrite': {
        'task': 'projectApp.tasks.generate_rss_articles',
        'schedule': crontab(hour='6,14,22', minute=0),
    },
    # Sports: EPL table + Super Eagles results + World Cup analysis (twice daily)
    'sports-articles': {
        'task': 'projectApp.tasks.generate_sports_articles',
        'schedule': crontab(hour='9,21', minute=0),
    },
    # Market: Brent crude, NGX index, agriculture commodities, ACLED security (twice daily)
    'market-articles': {
        'task': 'projectApp.tasks.generate_market_articles',
        'schedule': crontab(hour='8,20', minute=30),
    },
    # Politics: rotating Nigeria politics analysis (once daily, 10 AM UTC)
    'politics-articles': {
        'task': 'projectApp.tasks.generate_politics_articles',
        'schedule': crontab(hour=10, minute=0),
    },
}

# ── AI / Groq API (FREE) ───────────────────────────────────────────────────────
# Used by the data journalism + RSS rewrite Celery tasks to generate articles.
# Free key (no credit card): https://console.groq.com/keys
GROQ_API_KEY = config('GROQ_API_KEY', default='')

# ── ACLED Conflict Data API (FREE) ─────────────────────────────────────────────
# Required only for the Nigeria security briefing articles.
# Free account + key at: https://acleddata.com/register/
ACLED_API_KEY = config('ACLED_API_KEY', default='')
ACLED_EMAIL = config('ACLED_EMAIL', default='')



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUD_NAME'),
    'API_KEY': config('API_KEY'),
    'API_SECRET': config('API_SECRET'),
}

# ── Social Media Auto-Poster ───────────────────────────────────────────────────
# Full URL of the site — used to build article links in social posts
SITE_URL = config('SITE_URL', default='https://www.pulselinedaily.com')

# Facebook Page — get a Page Access Token at developers.facebook.com
# Needs pages_manage_posts + pages_read_engagement permissions
FACEBOOK_PAGE_ACCESS_TOKEN = config('FACEBOOK_PAGE_ACCESS_TOKEN', default='')
FACEBOOK_PAGE_ID = config('FACEBOOK_PAGE_ID', default='')

# Telegram Channel — create a bot via @BotFather, add it as admin to your channel
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHANNEL_ID = config('TELEGRAM_CHANNEL_ID', default='')

# OneSignal Push Notifications
ONESIGNAL_APP_ID = config('ONESIGNAL_APP_ID', default='')
ONESIGNAL_REST_API_KEY = config('ONESIGNAL_REST_API_KEY', default='')

# Admin draft notification email
ADMIN_NOTIFICATION_EMAIL = config('ADMIN_NOTIFICATION_EMAIL', default='')


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

cloudinary.config(
    cloud_name=config('CLOUD_NAME'),
    api_key=config('API_KEY'),
    api_secret=config('API_SECRET'),
    secure=True
)


# ── Cache ──────────────────────────────────────────────────────────────────────
# Production: shared Redis cache so all Gunicorn workers see the same state.
# Development: local in-memory cache (no Redis needed locally).
if ENVIRONMENT == 'production':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://redis:6379/1',  # DB 1 — Celery uses DB 0
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'pulselinedaily',
        }
    }

CACHE_MIDDLEWARE_SECONDS = 300


# ── Email (SMTP) ───────────────────────────────────────────────────────────────
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=True, cast=bool)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='PulseLineDaily <contact@pulselinedaily.com>'
)
SERVER_EMAIL = config('EMAIL_HOST_USER')

# All contact/advertise/notification emails are sent to this address
CONTACT_EMAIL = config('CONTACT_EMAIL', default='contact@pulselinedaily.com')




INTERNAL_API_TOKEN = config("INTERNAL_API_TOKEN", default="")
