from django.core.management.base import BaseCommand
from projectApp.models import GovernmentAgency

AGENCIES = [
    # ── Financial & Economic ──────────────────────────────────────────────────
    {
        'name': 'Central Bank of Nigeria',
        'acronym': 'CBN',
        'sector': 'financial',
        'website': 'https://www.cbn.gov.ng',
        'news_url': 'https://www.cbn.gov.ng/Documents/pressreleases.asp',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Federal Inland Revenue Service',
        'acronym': 'FIRS',
        'sector': 'financial',
        'website': 'https://www.firs.gov.ng',
        'news_url': 'https://www.firs.gov.ng/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Securities and Exchange Commission',
        'acronym': 'SEC',
        'sector': 'financial',
        'website': 'https://sec.gov.ng',
        'news_url': 'https://sec.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Debt Management Office',
        'acronym': 'DMO',
        'sector': 'financial',
        'website': 'https://www.dmo.gov.ng',
        'news_url': 'https://www.dmo.gov.ng/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Bureau of Statistics',
        'acronym': 'NBS',
        'sector': 'financial',
        'website': 'https://nigerianstat.gov.ng',
        'news_url': 'https://nigerianstat.gov.ng/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Insurance Commission',
        'acronym': 'NAICOM',
        'sector': 'financial',
        'website': 'https://www.naicom.gov.ng',
        'news_url': 'https://www.naicom.gov.ng/index.php/media/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Bank of Industry',
        'acronym': 'BOI',
        'sector': 'financial',
        'website': 'https://www.boi.ng',
        'news_url': 'https://www.boi.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Development Bank of Nigeria',
        'acronym': 'DBN',
        'sector': 'financial',
        'website': 'https://www.devbankng.com',
        'news_url': 'https://www.devbankng.com/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Budget Office of the Federation',
        'acronym': 'BOF',
        'sector': 'financial',
        'website': 'https://www.budgetoffice.gov.ng',
        'news_url': 'https://www.budgetoffice.gov.ng/index.php/resources/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Oil, Gas & Energy ─────────────────────────────────────────────────────
    {
        'name': 'NNPC Limited',
        'acronym': 'NNPCL',
        'sector': 'energy',
        'website': 'https://nnpcgroup.com',
        'news_url': 'https://nnpcgroup.com/media/press-releases/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Upstream Petroleum Regulatory Commission',
        'acronym': 'NUPRC',
        'sector': 'energy',
        'website': 'https://nuprc.gov.ng',
        'news_url': 'https://nuprc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Midstream and Downstream Petroleum Regulatory Authority',
        'acronym': 'NMDPRA',
        'sector': 'energy',
        'website': 'https://nmdpra.gov.ng',
        'news_url': 'https://nmdpra.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Electricity Regulatory Commission',
        'acronym': 'NERC',
        'sector': 'energy',
        'website': 'https://nerc.gov.ng',
        'news_url': 'https://nerc.gov.ng/index.php/media/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Rural Electrification Agency',
        'acronym': 'REA',
        'sector': 'energy',
        'website': 'https://rea.gov.ng',
        'news_url': 'https://rea.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigeria LNG',
        'acronym': 'NLNG',
        'sector': 'energy',
        'website': 'https://www.nlng.com',
        'news_url': 'https://www.nlng.com/Media/Pages/Press-Releases.aspx',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Telecoms & Technology ─────────────────────────────────────────────────
    {
        'name': 'Nigerian Communications Commission',
        'acronym': 'NCC',
        'sector': 'telecom',
        'website': 'https://ncc.gov.ng',
        'news_url': 'https://ncc.gov.ng/media-centre/news-headlines',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Information Technology Development Agency',
        'acronym': 'NITDA',
        'sector': 'telecom',
        'website': 'https://nitda.gov.ng',
        'news_url': 'https://nitda.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigeria Data Protection Commission',
        'acronym': 'NDPC',
        'sector': 'telecom',
        'website': 'https://ndpc.gov.ng',
        'news_url': 'https://ndpc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Health ────────────────────────────────────────────────────────────────
    {
        'name': 'National Agency for Food and Drug Administration and Control',
        'acronym': 'NAFDAC',
        'sector': 'health',
        'website': 'https://www.nafdac.gov.ng',
        'news_url': 'https://www.nafdac.gov.ng/category/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigeria Centre for Disease Control',
        'acronym': 'NCDC',
        'sector': 'health',
        'website': 'https://ncdc.gov.ng',
        'news_url': 'https://ncdc.gov.ng/news',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Health Insurance Authority',
        'acronym': 'NHIA',
        'sector': 'health',
        'website': 'https://nhia.gov.ng',
        'news_url': 'https://nhia.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Transport & Infrastructure ────────────────────────────────────────────
    {
        'name': 'Nigerian Ports Authority',
        'acronym': 'NPA',
        'sector': 'transport',
        'website': 'https://nigerianports.gov.ng',
        'news_url': 'https://nigerianports.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Federal Airports Authority of Nigeria',
        'acronym': 'FAAN',
        'sector': 'transport',
        'website': 'https://faan.gov.ng',
        'news_url': 'https://faan.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Civil Aviation Authority',
        'acronym': 'NCAA',
        'sector': 'transport',
        'website': 'https://ncaa.gov.ng',
        'news_url': 'https://ncaa.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Federal Road Safety Corps',
        'acronym': 'FRSC',
        'sector': 'transport',
        'website': 'https://frsc.gov.ng',
        'news_url': 'https://frsc.gov.ng/frsc/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Railway Corporation',
        'acronym': 'NRC',
        'sector': 'transport',
        'website': 'https://nrc.gov.ng',
        'news_url': 'https://nrc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Environment & Agriculture ─────────────────────────────────────────────
    {
        'name': 'Nigerian Meteorological Agency',
        'acronym': 'NiMet',
        'sector': 'environment',
        'website': 'https://nimet.gov.ng',
        'news_url': 'https://nimet.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Environmental Standards and Regulations Enforcement Agency',
        'acronym': 'NESREA',
        'sector': 'environment',
        'website': 'https://nesrea.gov.ng',
        'news_url': 'https://nesrea.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Oil Spill Detection and Response Agency',
        'acronym': 'NOSDRA',
        'sector': 'environment',
        'website': 'https://nosdra.gov.ng',
        'news_url': 'https://nosdra.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Agricultural Development Fund',
        'acronym': 'NADF',
        'sector': 'environment',
        'website': 'https://nadf.gov.ng',
        'news_url': 'https://nadf.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Anti-Corruption & Justice ─────────────────────────────────────────────
    {
        'name': 'Economic and Financial Crimes Commission',
        'acronym': 'EFCC',
        'sector': 'justice',
        'website': 'https://efcc.gov.ng',
        'news_url': 'https://efcc.gov.ng/news/press-releases/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Independent Corrupt Practices and Other Related Offences Commission',
        'acronym': 'ICPC',
        'sector': 'justice',
        'website': 'https://www.icpc.gov.ng',
        'news_url': 'https://www.icpc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Drug Law Enforcement Agency',
        'acronym': 'NDLEA',
        'sector': 'justice',
        'website': 'https://ndlea.gov.ng',
        'news_url': 'https://ndlea.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Development & Investment ──────────────────────────────────────────────
    {
        'name': 'Niger Delta Development Commission',
        'acronym': 'NDDC',
        'sector': 'development',
        'website': 'https://nddc.gov.ng',
        'news_url': 'https://nddc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'North East Development Commission',
        'acronym': 'NEDC',
        'sector': 'development',
        'website': 'https://nedc.gov.ng',
        'news_url': 'https://nedc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Investment Promotion Commission',
        'acronym': 'NIPC',
        'sector': 'development',
        'website': 'https://nipc.gov.ng',
        'news_url': 'https://nipc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Small and Medium Enterprises Development Agency of Nigeria',
        'acronym': 'SMEDAN',
        'sector': 'development',
        'website': 'https://www.smedan.gov.ng',
        'news_url': 'https://www.smedan.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Bank of Agriculture',
        'acronym': 'BOA',
        'sector': 'development',
        'website': 'https://www.boanig.com',
        'news_url': 'https://www.boanig.com/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Export Promotion Council',
        'acronym': 'NEPC',
        'sector': 'development',
        'website': 'https://nepc.gov.ng',
        'news_url': 'https://nepc.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Education ─────────────────────────────────────────────────────────────
    {
        'name': 'National Universities Commission',
        'acronym': 'NUC',
        'sector': 'education',
        'website': 'https://nuc.edu.ng',
        'news_url': 'https://nuc.edu.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Joint Admissions and Matriculation Board',
        'acronym': 'JAMB',
        'sector': 'education',
        'website': 'https://www.jamb.gov.ng',
        'news_url': 'https://www.jamb.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'West African Examinations Council Nigeria',
        'acronym': 'WAEC',
        'sector': 'education',
        'website': 'https://waeconline.org.ng',
        'news_url': 'https://waeconline.org.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Board for Technical Education',
        'acronym': 'NBTE',
        'sector': 'education',
        'website': 'https://nbte.gov.ng',
        'news_url': 'https://nbte.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Tertiary Education Trust Fund',
        'acronym': 'TETFund',
        'sector': 'education',
        'website': 'https://tetfund.gov.ng',
        'news_url': 'https://tetfund.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Labour, Pension & Immigration ─────────────────────────────────────────
    {
        'name': 'Nigeria Immigration Service',
        'acronym': 'NIS',
        'sector': 'labour',
        'website': 'https://immigration.gov.ng',
        'news_url': 'https://immigration.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'National Pension Commission',
        'acronym': 'PenCom',
        'sector': 'labour',
        'website': 'https://www.pencom.gov.ng',
        'news_url': 'https://www.pencom.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Industrial Training Fund',
        'acronym': 'ITF',
        'sector': 'labour',
        'website': 'https://itf.gov.ng',
        'news_url': 'https://itf.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigeria Social Insurance Trust Fund',
        'acronym': 'NSITF',
        'sector': 'labour',
        'website': 'https://nsitf.gov.ng',
        'news_url': 'https://nsitf.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Security & Defence ────────────────────────────────────────────────────
    {
        'name': 'Nigeria Police Force',
        'acronym': 'NPF',
        'sector': 'security',
        'website': 'https://npf.gov.ng',
        'news_url': 'https://npf.gov.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    {
        'name': 'Nigerian Army',
        'acronym': 'NA',
        'sector': 'security',
        'website': 'https://army.mil.ng',
        'news_url': 'https://army.mil.ng/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
    # ── Elections & Democracy ─────────────────────────────────────────────────
    {
        'name': 'Independent National Electoral Commission',
        'acronym': 'INEC',
        'sector': 'elections',
        'website': 'https://www.inecnigeria.org',
        'news_url': 'https://www.inecnigeria.org/news/',
        'rss_url': None,
        'scrape_strategy': 'html',
    },
]


class Command(BaseCommand):
    help = 'Seed all 51 Nigerian government agencies into the database (safe to re-run)'

    def handle(self, *args, **options):
        created = updated = 0

        for data in AGENCIES:
            agency, was_created = GovernmentAgency.objects.update_or_create(
                acronym=data['acronym'],
                defaults={
                    'name': data['name'],
                    'sector': data['sector'],
                    'website': data['website'],
                    'news_url': data['news_url'],
                    'rss_url': data.get('rss_url'),
                    'scrape_strategy': data['scrape_strategy'],
                    'is_active': True,
                    'priority': 1,
                },
            )
            if was_created:
                created += 1
                self.stdout.write(self.style.SUCCESS(f'  Created: {agency}'))
            else:
                updated += 1
                self.stdout.write(f'  Updated: {agency}')

        self.stdout.write(self.style.SUCCESS(
            f'\nDone — {created} created, {updated} updated. '
            f'Total: {created + updated} agencies.'
        ))
