# Generated by Django 5.2.4 on 2025-07-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.CharField(default='Chinny N.', max_length=100),
        ),
    ]
