# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_alter_post_date_created_alter_post_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=300, blank=True, null=True, help_text='Comma-separated keywords/tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_domain',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Total word count'),
        ),
    ]
