# Generated by Django 5.2.4 on 2025-09-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_advertisement_author_contactmessage_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='breaking_expiry',
            field=models.DateTimeField(blank=True, help_text='Breaking news expiry time', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_breaking',
            field=models.BooleanField(default=False, help_text='Mark as breaking news'),
        ),
    ]
