# Generated by Django 5.2.4 on 2025-09-15 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_post_breaking_expiry_post_is_breaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, default='Clinton Nwachukwu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='projectApp.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.CharField(default='Clinton Nwachukwu', max_length=100),
        ),
    ]
