# Generated by Django 5.2.4 on 2025-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_remove_post_videos_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_profile',
            field=models.URLField(blank=True, help_text="Link to author's social media (Twitter, LinkedIn, etc.)", null=True),
        ),
    ]
