# Generated by Django 5.2.4 on 2025-10-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_post_extra_fields'),
        ('projectApp', '0009_author_social_profile'),
    ]

    operations = [
    ]
