# Generated by Django 5.2.4 on 2025-10-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_merge_20251007_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('scrape', 'Scrape')], default='manual', max_length=10),
        ),
    ]
