# Generated by Django 5.2.4 on 2025-10-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0012_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
