# Generated by Django 5.2.4 on 2025-10-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0013_applicant_applied_on_applicant_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='projectApp.job'),
        ),
    ]
