# Generated by Django 6.0.3 on 2026-06-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0016_comment_is_approved_post_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Only approved comments are shown publicly'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=False, help_text='True only after email confirmation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_breaking',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as breaking news'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Schedule publish date/time. Leave blank to publish immediately.', null=True),
        ),
    ]
