# Generated by Django 6.0.3 on 2026-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0017_newslettersubscriber_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
