# Generated by Django 6.0.3 on 2026-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0019_governmentagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide a comment from public view'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to unsubscribe this address'),
        ),
    ]
