# Generated by Django 6.0.3 on 2026-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpostlog',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('telegram', 'Telegram'), ('onesignal', 'Push Notification')], max_length=20),
        ),
    ]
